### ISSUE TITLE
Boost Heroku's Competitive Edge: Add postgres LLM Embedding Vectorization Support

### ISSUE THREAD

**Issue by br4e** [heroku/roadmap#168] opened 2023-04-10 15:36 UTC
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Postgres

### Tell us about what you're trying to solve. What challenges are you facing?

**Boost Heroku's Competitive Edge: Add postgres LLM Embedding Vectorization Support**

**TL;DR: Add pgvector or a similar extension for PostgreSQL on Heroku to support efficient LLM embedding vectorization, cater to growing demand for AI applications, and stay competitive against alternatives like Pinecone.**

As the demand for AI-powered applications, particularly those utilizing large language models (LLMs) like ChatGPT, continues to grow, I propose adding pgvector or any other suitable solution to Heroku's list of supported PostgreSQL extensions.

The current lack of support for PostgreSQL extensions that enable efficient AI LLM embedding vectorization, such as pgvector (https://github.com/pgvector/pgvector), is hindering Heroku's ability to cater to this growing market. By adding pgvector or similar solutions, you would enable developers to store, index, and work with ChatGPT and other LLM vectors more effectively on the Heroku platform.

Currently, alternative services like Pinecone (https://www.pinecone.io/) are seizing this opportunity and attracting developers looking for efficient ways to index and manage their embedding vectors. Heroku's current PostgreSQL extension offerings (https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search) do not include any suitable options for this purpose, placing Heroku at a competitive disadvantage.

To maintain Heroku's strong position in the market and cater to the growing number of developers building LLM-based applications, I kindly request the addition of pgvector support or similar solutions as soon as possible. Without this support, I, like many others, may have to turn to Pinecone for my vector indexing needs instead of relying on Heroku's services.

Thank you for considering this proposal, and I look forward to seeing pgvector or a comparable solution integrated into Heroku's PostgreSQL offerings.

See also: https://github.com/heroku/roadmap/issues/156

**Comment by br4e** [comment] 2023-04-10 15:38
see also:

https://github.com/heroku/roadmap/issues/156

**Comment by jbrown-heroku** [comment] 2023-05-05 00:41
This is a great suggestion and we definitely want to expand capabilities around our data offerings. Thank you @br4e. We will look into this.

**Comment by jbrown-heroku** [comment] 2024-01-19 22:22
Duplicate of https://github.com/heroku/roadmap/issues/156
Shipped in 2023! https://blog.heroku.com/pgvector-launch
Closing this.

**Closed by jbrown-heroku** 2024-01-19 22:22 UTC
Labels: Data
